# docker-compose.yml - For Cloudflare/RepoCloud.io delegated SSL or local development
# (This is your original default docker-compose.yml)
version: "3.8"

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      # This mapping is for the 3rd party delegated SSL scenario (e.g., Cloudflare forwarding to host port 80)
      - "80:${PORT:-8888}"
      # This mapping is for direct local development access from your frontend
      - "${PORT:-8888}:${PORT:-8888}" # Maps host port 8888 to container port 8888
    env_file:
      - ./.env

    volumes:
      - app_data:/data

volumes:
  app_data:
    driver: local
