# docker-compose.yml - For local development and automated CI testing
version: "3.8"

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      # This mapping is for the 3rd party delegated SSL scenario (e.g., Cloudflare)
      - "80:${PORT:-8888}"
      # This mapping is for direct local development access
      - "${PORT:-8888}:${PORT:-8888}"
    env_file:
      - ./.env

    volumes:
      - app_data:/data

    # NEW: Healthcheck for the app service to ensure it's ready before tests run.
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-8888}/health"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

  newman:
    image: postman/newman:latest
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./:/etc/newman
    env_file:
      - ./.env
    command: ["run", "postman/postman-rest-api.json"]

volumes:
  app_data:
    driver: local
